name: n_dimensional_array
description: Allows for the creation and easy manipulation of n-dimensional
  arrays in Dart.
version: 1.0.4
repository: https://github.com/babincc/n_dimensional_array
issue_tracker: https://github.com/babincc/n_dimensional_array/issues

topics:
  - multidimensional-array
  - nested-list

funding:
  - https://www.buymeacoffee.com/babincc
  - https://paypal.me/cssbabin
  - https://venmo.com/u/babincc

environment:
  sdk: ^3.6.1

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.4
